- demo/Demo.js
- demo/app.css
- demo/index.html
- package.json
- src/PlacesAutocomplete.js
> Allow ESC key to clear autocomplete dropdown

- README.md
- src/PlacesAutocomplete.js
- src/index.js
- src/utils.js
Provide placeId using onSelect callback function. 
Also added `geocodeByPlceId` helper function as a named export.
Resolves #13
> Allow user to use placeId

- README.md
- src/utils.js
> Provide entire results from Google API through callbacks

- README.md
- demo/Demo.js
- src/PlacesAutocomplete.js
Allow user to provide input name via props
Resolves #31
> feat(props): Add inputName prop

- README.md
- demo/Demo.js
- src/PlacesAutocomplete.js
- src/PlacesAutocompleteBasic.js
- src/PlacesAutocompleteWithTypeAhead.js
- src/tests/index.spec.js
BREAKING CHANGE: Finally added soft autocomplete feature. Major version update!
> feat(typeAhead): Add soft autocomplete feature

- src/PlacesAutocompleteWithTypeAhead.js
Fixed minor bug with typeAhead feature
> fix(typeAhead): Fix keydown event handler

- README.md
- src/PlacesAutocomplete.js
- src/PlacesAutocompleteBasic.js
- src/PlacesAutocompleteWithTypeAhead.js
> feat(prop): Allow user to pass id for input field

- src/PlacesAutocompleteBasic.js
- src/PlacesAutocompleteWithTypeAhead.js
>  Fix keydown event handler when no autocomplete items exist

- README.md
- src/PlacesAutocomplete.js
- src/tests/testHelper.js
> Show meaningful error message when google library is not available

- README.md
- demo/Demo.js
- src/index.js
- src/utils.js
> Add Promise support to geocoding functions

- README.md
- src/PlacesAutocomplete.js
Allow user to highlight the first suggestion in the dropdown
Closes #23
> Add highlightFirstSuggestion prop

- src/PlacesAutocomplete.js
> Fix error thrown by Google API when sending request with empty input value

- src/PlacesAutocomplete.js
> Add default autocomplete='off' to input element

- package.json
> Remove react from dependencies and move it to peerDependencies list

- README.md
- demo/Demo.js
- src/PlacesAutocomplete.js
Change function signature of `onError` to
```js
function onError(status, clearSuggesion) 
```
Removed `clearSuggesionsOnError` prop
> Allow user to clear suggestions using `onError` prop

- src/PlacesAutocomplete.js
> Fix mobile touch event handler bug

- demo/components/SearchBar.js
- src/PlacesAutocomplete.js
> Fix onSelect handler

- src/PlacesAutocomplete.js
- src/tests/helpers/setup.js
- src/tests/loading.test.js
* Bump to version 7.2.0
* Add loading to internal state
* Expose loading status to render prop
* Add hooks for modifying loading status
Exposing loading status to render so that users can easily add spinners/etc during loading
> Make loading prop available to child components

- README.md
Sorry, forgot to update the README with information about the new prop, I realized it right after you merged.
> update README.md with loading prop

- README.md
**Summary**
This change is intended to raise awareness for the possibility to join as a maintainer or have a fork be credited in the README, [as mentioned by the project owner](https://github.com/hibiken/react-places-autocomplete/issues/296#issuecomment-583764730
).
> Add maintainers-wanted section to README

- package-lock.json
**Summary**
Updated the npm lockfile on the basis of b3d1b5c1491687916778d1d9064bf7926e8174a2
> Update npm lockfile

- README.md
Added this change as I'm noticing even more that the project requires more attention and I will not be able to cover that entirely.
> Emphasize need for additional maintainers in README
